#!/bin/bash

command=$1
shift

null() { $@ 1>/dev/null 2>/dev/null; }

if [[ $command == "run" ]] || [[ $command == "" ]]; then
	STOPPED_CONTAINER_ID=$(docker ps -f name=motherbox --all -q)
	if [[ $STOPPED_CONTAINER_ID != "" ]]; then
		echo "Starting Container $STOPPED_CONTAINER_ID..."
		null docker start $STOPPED_CONTAINER_ID
	fi
	RUNNING_CONTAINER_ID=$(docker ps -f name=motherbox -q)
	if [[ $RUNNING_CONTAINER_ID != "" ]]; then
		echo "Attaching Container $RUNNING_CONTAINER_ID..."
		docker exec -it $RUNNING_CONTAINER_ID bash
	else
		echo "No Existing Container Found."
		echo "Creating Container..."
		docker run $@ --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
			--name motherbox -p 8001-8010:8001-8010 -h motherbox -v $MOTHERBOX:/code -it motherbox
	fi
elif [[ $command == "build" ]]; then
	RUNNING_CONTAINER_ID=$(docker ps -f name=motherbox -q)
	if [[ $RUNNING_CONTAINER_ID != "" ]]; then
		echo "Stopping Container $RUNNING_CONTAINER_ID..."
		null docker stop $RUNNING_CONTAINER_ID
	fi
	STOPPED_CONTAINER_ID=$(docker ps -f name=motherbox -q --all)
	if [[ $STOPPED_CONTAINER_ID != "" ]]; then
		echo "Removing Container $STOPPED_CONTAINER_ID..."
		null docker rm $STOPPED_CONTAINER_ID
	fi
	cd $MOTHERBOX
	docker build $@ . -t motherbox:latest
fi
